// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOWq0joXjXe8P0CeneWbyEpeFVYatt6ic',
    appId: '1:574255748909:web:244c00592383f6f80be5a4',
    messagingSenderId: '574255748909',
    projectId: 'fir-ticketing-cd8e9',
    authDomain: 'fir-ticketing-cd8e9.firebaseapp.com',
    storageBucket: 'fir-ticketing-cd8e9.appspot.com',
    measurementId: 'G-GNLS7RBPLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwH33qtebGWsYSchwDT4Jc-u-h0UHgBEA',
    appId: '1:574255748909:android:95fb875802d3581f0be5a4',
    messagingSenderId: '574255748909',
    projectId: 'fir-ticketing-cd8e9',
    storageBucket: 'fir-ticketing-cd8e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADICLhxs1znMhM6BIq1-Z5YC4NvkwjeSU',
    appId: '1:574255748909:ios:9840218ffc9d81ae0be5a4',
    messagingSenderId: '574255748909',
    projectId: 'fir-ticketing-cd8e9',
    storageBucket: 'fir-ticketing-cd8e9.appspot.com',
    iosBundleId: 'com.example.ticketingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOWq0joXjXe8P0CeneWbyEpeFVYatt6ic',
    appId: '1:574255748909:web:95efd3b85177cd680be5a4',
    messagingSenderId: '574255748909',
    projectId: 'fir-ticketing-cd8e9',
    authDomain: 'fir-ticketing-cd8e9.firebaseapp.com',
    storageBucket: 'fir-ticketing-cd8e9.appspot.com',
    measurementId: 'G-HFW89Y2523',
  );

}